"""Build tasks.json from HSD-ES query results and local resource registry.

Flow:
1. Load config IDs from resource_registry.json.
2. Fetch child articles via HSD-ES query.
3. Fetch parent articles (deduplicated by parent_id) to read priority.
4. Build task objects.

Behavior:
- If any article has config_id not present in resource registry, print all unmatched
  tasks and exit without writing output.
- task_id is generated by slugifying article title.
- Commands are composed from automation framework pre-commands + command_line.
"""

from __future__ import annotations

import argparse
import json
import os
import re
from pathlib import Path
from typing import Any

from lib.hsdes_client import HsdesClient

CONFIG_ID_FIELD = "server_platf.test_case.configuration_id"
AUTOMATION_FRAMEWORKS_FIELD = "server_platf.test_case.automation_frameworks"
COMMAND_LINE_FIELD = "server_platf.test_case.command_line"

PRE_COMMANDS: dict[str, list[str]] = {
    "Kayak": [
        r"cd {KAYAK_PATH}",
        r"Powershell.exe -NonInteractive -File src\kayak\scripts\setup_kayak.ps1",
    ],
}


def _normalize_articles(data: Any) -> list[dict[str, Any]]:
    if data is None:
        return []
    if isinstance(data, list):
        return [item for item in data if isinstance(item, dict)]
    if isinstance(data, dict):
        return [data]
    return []


def slugify_task_id(title: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", title.strip())
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    return cleaned or "task"


def _to_positive_int(value: Any, field_name: str) -> int:
    try:
        parsed = int(str(value).strip())
    except Exception as exc:
        raise ValueError(f"invalid {field_name}: {value!r}") from exc
    if parsed <= 0:
        raise ValueError(f"{field_name} must be positive, got {parsed}")
    return parsed


def _resolve_env_path(name: str) -> str:
    value = os.getenv(name)
    if value is None:
        raise ValueError(f"environment variable {name!r} is required")

    cleaned = value.strip()
    if len(cleaned) >= 2 and cleaned[0] == cleaned[-1] and cleaned[0] in {'"', "'"}:
        cleaned = cleaned[1:-1].strip()
    if not cleaned:
        raise ValueError(f"environment variable {name!r} must not be empty")
    return cleaned


def get_pre_commands(framework: str) -> list[str]:
    template = PRE_COMMANDS.get(framework, [])
    if framework != "Kayak" or not template:
        return list(template)

    kayak_path = _resolve_env_path("KAYAK_PATH")
    return [line.replace("{KAYAK_PATH}", kayak_path) for line in template]


def load_registry_config_ids(registry_file: Path) -> set[int]:
    raw = json.loads(registry_file.read_text(encoding="utf-8"))
    resources = raw.get("resources") if isinstance(raw, dict) else None
    if not isinstance(resources, list):
        raise ValueError("resource registry must contain a 'resources' list")

    config_ids: set[int] = set()
    for item in resources:
        if not isinstance(item, dict):
            continue
        config_ids.add(_to_positive_int(item.get("config_id"), "registry config_id"))
    return config_ids


def fetch_parent_articles(
    client: HsdesClient,
    child_articles: list[dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    parent_ids = {
        str(article.get("parent_id")).strip()
        for article in child_articles
        if article.get("parent_id") not in (None, "")
    }

    result: dict[str, dict[str, Any]] = {}
    for parent_id in sorted(parent_ids):
        parent_response = client.get_article(_to_positive_int(parent_id, "parent_id"))
        if not parent_response.get("ok"):
            raise RuntimeError(
                f"failed to fetch parent article {parent_id}: "
                f"{parent_response.get('error')}"
            )
        articles = _normalize_articles(parent_response.get("data"))
        if articles:
            result[parent_id] = articles[0]
    return result


def build_tasks_from_articles(
    child_articles: list[dict[str, Any]],
    parent_articles: dict[str, dict[str, Any]],
    known_config_ids: set[int],
    default_priority: int,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    tasks: list[dict[str, Any]] = []
    unmatched: list[dict[str, Any]] = []
    seen_task_ids: set[str] = set()

    for article in child_articles:
        article_id = str(article.get("id", "")).strip() or "<unknown>"
        title = str(article.get("title", "")).strip()
        if not title:
            raise ValueError(f"article {article_id} missing title")

        config_id = _to_positive_int(article.get(CONFIG_ID_FIELD), CONFIG_ID_FIELD)
        if config_id not in known_config_ids:
            unmatched.append(
                {
                    "article_id": article_id,
                    "title": title,
                    "config_id": config_id,
                }
            )
            continue

        command_line = str(article.get(COMMAND_LINE_FIELD, "")).strip()
        if not command_line:
            raise ValueError(f"article {article_id} missing command_line field {COMMAND_LINE_FIELD!r}")

        framework = str(article.get(AUTOMATION_FRAMEWORKS_FIELD, "")).strip()
        commands = [*get_pre_commands(framework), command_line]

        parent_id = str(article.get("parent_id", "")).strip()
        priority = default_priority
        if parent_id:
            parent_article = parent_articles.get(parent_id)
            if parent_article is not None:
                parent_priority = parent_article.get("priority")
                if parent_priority not in (None, ""):
                    priority = _to_positive_int(parent_priority, "priority")

        task_id = slugify_task_id(title)
        if task_id in seen_task_ids:
            raise ValueError(
                f"duplicate task_id generated from titles: {task_id!r}; "
                "please adjust titles to be unique"
            )
        seen_task_ids.add(task_id)

        tasks.append(
            {
                "task_id": task_id,
                "config_id": config_id,
                "priority": priority,
                "commands": commands,
            }
        )

    return tasks, unmatched


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build tasks.json from HSD-ES query")
    parser.add_argument("--registry", required=True, help="Path to resource_registry.json")
    parser.add_argument("--query-id", required=True, type=int, help="HSD-ES query id")
    parser.add_argument("--output", required=True, help="Path to output tasks.json")
    parser.add_argument("--default-priority", type=int, default=100, help="Fallback priority")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if args.default_priority <= 0:
        raise ValueError("--default-priority must be a positive integer")

    known_config_ids = load_registry_config_ids(Path(args.registry))

    client = HsdesClient()
    query_response = client.get_query(args.query_id)
    if not query_response.get("ok"):
        raise RuntimeError(f"failed to run query {args.query_id}: {query_response.get('error')}")

    child_articles = _normalize_articles(query_response.get("data"))
    parent_articles = fetch_parent_articles(client, child_articles)
    tasks, unmatched = build_tasks_from_articles(
        child_articles=child_articles,
        parent_articles=parent_articles,
        known_config_ids=known_config_ids,
        default_priority=args.default_priority,
    )

    if unmatched:
        print("Found tasks with config_id not in resource registry:")
        for item in unmatched:
            print(
                "- article_id={article_id}, config_id={config_id}, title={title}".format(
                    **item
                )
            )
        print("Please add matching resources into resource_registry.json and rerun.")
        return 2

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps({"tasks": tasks}, indent=2), encoding="utf-8")
    print(f"Wrote {len(tasks)} tasks to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
